# Banking Churn Modelling  
Deep Learning Model  
_Artificial Neural Netrwork_  
Author : __Abhijit Mandal__

_Importing the libraries_

In [62]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [63]:
tf.__version__

'2.16.1'

# Part 1 - Data Preprocessing

_Importing the Dataset_

In [64]:
df = pd.read_csv(r"..\\Data\\Churn_Modelling.csv", encoding = 'latin1')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

_Checking for the Null values here_

In [65]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [66]:
df.isnull().sum().sum()

0

_Separating the features here_
- `Exited` is the dependent feature.

In [67]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

_Excluding the irrelavent features here_
- RowNumber
- CustomerID
- SurName

In [68]:
X = df.iloc[:, 3:-1]
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [69]:
print(y)

[1 0 1 ... 1 1 0]


_Encoding the Categorical Data_

_Label encoding the `gender` column_

In [70]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X.iloc[:, 2] = le.fit_transform(X.iloc[:, 2])

_`Gender` column after Label Encoding_
- `0` - `Female`
- `1` - `Male`

In [71]:
X.tail()

CreditScore Geography Gender  Age  Tenure    Balance  NumOfProducts  \
9995          771    France      1   39       5       0.00              2   
9996          516    France      1   35      10   57369.61              1   
9997          709    France      0   36       7       0.00              1   
9998          772   Germany      1   42       3   75075.31              2   
9999          792    France      0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78

_One Hot Encoding the `Geography` column_

In [72]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [73]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


_Splitting the dataset into training and test set_

In [74]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

_Feature Scaling_
* Very important step for deep learning models.

In [75]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Part 2 -  Building the ANN

- _Initializing the ANN_

In [76]:
ann = tf.keras.models.Sequential()

- _Adding the input layer and the first hidden layer_

In [77]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

- _Adding the second hidden layer_

In [78]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

- _Adding the output layer_

In [79]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Part 3 - Training the ANN

- _Compiling the ANN_

In [80]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

- _Training the ANN on the Training Set_

In [81]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 751us/step - accuracy: 0.6038 - loss: 0.6716
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 746us/step - accuracy: 0.7923 - loss: 0.5157
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7963 - loss: 0.4708
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8039 - loss: 0.4410
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 734us/step - accuracy: 0.8129 - loss: 0.4257
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.8241 - loss: 0.4179
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8227 - loss: 0.4101
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.8293 - loss: 0.4034
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.8366 - loss: 0.3901
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.8359 - loss: 0.3957
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.8385 - loss: 0.3869
Epoch 12/100
250/250 ━━

`Best Accuracy` : `86.54%`

# Part 4 - Making the predictions and evaluating the model.

_Predicting the result of a single observation._

Use the ANN model to predict the customer with the following info. will leave the bank:

- Geography: `France`
- Credit Score: `600`
- Gender: `Male`
- Age: `40 years old`
- Tenure: `3 years`
- Balance: `\$ 60000`
- Number of Products: `2`
- Does this customer have a credit card? `Yes`
- Is this customer an Active Member: `Yes`
- Estimated Salary: `\$ 50000`

So, should we say goodbye to that customer?

_As we have performed scaling while training the model so we need to scale it again while making predictions as well._

_The below code will give the probability of the fact whether the customer will leaves the bank or not._

In [82]:
# 1,0,0 -> France (dummy var)
print(ann.predict(sc.transform([[1,0,0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
[[0.03940224]]


_So as to make it give the result in `1` or `0` we just need to add a threshold as we have applied Sigmoid func. so 0.5 will be the threshold to predict._

In [83]:
probability = ann.predict(sc.transform([[1,0,0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))
if probability > 0.5:
    print('True') # customer will leave.
else:
    print("False") # customer will not leave.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
False


In [84]:
# aliter method.
print(ann.predict(sc.transform([[1,0,0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
[[False]]


_Predicting the Test Set Result_

In [85]:
y_pred = ann.predict(X_test)
y_pred = y_pred > 0.5

# predicted - actual
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


_Creating the Confusion Matrix_

In [86]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1520   75]
 [ 200  205]]


0.8625